### PR TITLE
steam, yandex

### PR DESCRIPTION
**Pull request by Cvar1984**

### CODE REVIEW

**Comment by ryukora** [comment]
ini apa? bukannya steam dan yandex gak keblokir lagi?

**Comment by Cvar1984** [comment]
> ini apa? bukannya steam dan yandex gak keblokir lagi? mohon dikasih deskripsi alasan nya kenapa untuk menambahkan situs yang tidak keblokir? ini sudah lewat dari jaman blokir pse

you should add it because everyone using it, if this apps is only for indonesia comunity its ok i'll do it myself

**Comment by ryukora** [comment]
> ini apa? bukannya steam dan yandex gak keblokir lagi? mohon dikasih deskripsi alasan nya kenapa untuk menambahkan situs yang tidak keblokir? ini sudah lewat dari jaman blokir pse
> 
> you should add it because everyone using it, its to avoid mitm phising, and not every country is steam availabe if this apps is indonesian only its ok i'll do it myself

steam and yandex are not blocked, they're on PSE's add list which yandex has and it enforces to use the filter of any porn sites

**Comment by Cvar1984** [comment]
> 

im not talking about indonesian pse policy im talking about everyone

**Comment by SlashyID** [comment]
**We're sorry for the inconvenience**

BebasID Host file is only designed to bypass Indonesian censorship and not made for other country.

If you want to use the equivalent, I recommend you to use [BebasDNS](https://github.com/bebasid/bebasdns) which has encrypted DNS feature such as DoH/DoT. 

With encrypted DNS, MITM is impossible since DoH/DoT encrypt the query request.

Host file isn't a great idea for a long-term solution because you need to update the host file manually if the IP is updated

**Pull request closed without merging**
